# Generated by Django 5.1.3 on 2024-11-22 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="JobPosting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=255)),
                ("title", models.CharField(max_length=255)),
                ("upper_region", models.CharField(max_length=255)),
                ("lower_region", models.CharField(max_length=255)),
                ("salary", models.CharField(max_length=255)),
                ("upper_field", models.CharField(max_length=255)),
                ("lower_field", models.CharField(max_length=255)),
                ("post_date", models.DateField()),
                ("due_date", models.DateField()),
                ("description", models.TextField()),
                (
                    "company_address",
                    models.CharField(default="Unknown", max_length=255),
                ),
                ("recruit_conditions", models.JSONField(blank=True, null=True)),
                ("work_conditions", models.JSONField(blank=True, null=True)),
                ("welfare_conditions", models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Resume",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="resumes/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resumes",
                        to="jobs.jobposting",
                    ),
                ),
            ],
        ),
    ]
