# Generated by Django 5.1.3 on 2024-11-14 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_answer_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="answer",
            name="modify_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="question",
            name="modify_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
